### ISSUE TITLE
你好，请教个问题

### ISSUE THREAD

**Issue by jialiQAQ** [PhoneTools/ComposeLocation#1]
我最近也在做一个关于GPS的项目。在Android 11 上 GnssStatus.hasBasebandCn0DbHz 和 GnssMeasurement.hasBasebandCn0DbHz 都为False，因此获取不到BaseBandCn0DbHz，但是能获取到Cn0DbHz。不知道是不是有什么特殊技巧。。
测试手机：pixel 3a Android 11，模拟器 Android 11 及Android 12.

**Comment by benjaminwan** [comment]
hasBasebandCn0DbHz=false就是代表不支持，我觉得不存在什么特殊技巧。

**Comment by jialiQAQ** [comment]
验证了，确实没啥关系，应该是跟卫星信号有关。谢谢。
