### ISSUE TITLE
lateinit property INSTANCE has not been initialized

### ISSUE THREAD

**Issue by parkodee** [PhoneTools/ComposeLocation#2]
When trying to run the app i got this exception

`.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property INSTANCE has not been initialized`

**Comment by benjaminwan** [comment]
v1.3.0: Replace lateinit with lazyinit

**Comment by parkodee** [comment]
I had to pass the main activity so I can use it there .
Thankx for the update
